// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc-IXa5SjXPnlVks-27e4InhX9XkIszxw',
    appId: '1:1017977266025:android:a1263040886b25da4ae7f8',
    messagingSenderId: '1017977266025',
    projectId: 'kidscar-454dd',
    databaseURL: 'https://kidscar-454dd-default-rtdb.firebaseio.com',
    storageBucket: 'kidscar-454dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3CD_2k4b5sOFEALCdUQ4J3T6B01QpOqM',
    appId: '1:1017977266025:ios:a558df4801fe8ffa4ae7f8',
    messagingSenderId: '1017977266025',
    projectId: 'kidscar-454dd',
    databaseURL: 'https://kidscar-454dd-default-rtdb.firebaseio.com',
    storageBucket: 'kidscar-454dd.firebasestorage.app',
    iosBundleId: 'com.codge.kidscar',
  );

}